export type CourseLesson = { title: string; topics: string[] };

export type Course = {
  slug: string;
  icon: string;
  title: string;
  tone: 'blue' | 'green' | 'cyan' | 'slate';
  gridDescription: string;
  badge: string;
  tagline: string;
  duration: string;
  mode: string;
  overview: string[];
  tools: string[];
  curriculum: CourseLesson[];
};

export const courses: Course[] = [
  {
    slug: 'ui-ux-design',
    icon: '✣',
    title: 'UI/UX Design',
    tone: 'blue',
    gridDescription: 'Design your ideas for real-world users.',
    badge: 'DESIGN-FOCUSED COURSE',
    tagline: 'Wireframing, prototyping and visual design for real products',
    duration: '3 Months',
    mode: 'Physical & Online Live Classes (Day/Night)',
    overview: [
      'The UI/UX Design course from Leafclutch is built for anyone who wants to design digital products that people actually enjoy using. You will learn how to research users, structure information, wireframe screens and turn them into polished, high-fidelity interfaces.',
      'Through hands-on projects, you will practice the same workflow professional designers use every day — from a rough sketch to a fully interactive prototype — and finish with a portfolio-ready case study you can show employers or clients.',
    ],
    tools: ['Figma', 'Adobe XD', 'FigJam', 'Photoshop', 'Illustrator', 'Notion', 'Zeplin', 'Miro'],
    curriculum: [
      { title: 'Lesson 1: Foundations of UI/UX', topics: ['What is UI vs UX', 'Design thinking process', 'Industry tools overview'] },
      { title: 'Lesson 2: User Research & Wireframing', topics: ['User personas & journeys', 'Low-fidelity wireframes', 'Information architecture'] },
      { title: 'Lesson 3: Visual Design Principles', topics: ['Typography & color theory', 'Grids and spacing', 'Design systems'] },
      { title: 'Lesson 4: Prototyping in Figma', topics: ['Auto layout & components', 'Interactive prototypes', 'Handoff to developers'] },
      { title: 'Lesson 5: Portfolio Project', topics: ['End-to-end case study', 'Usability testing', 'Presenting your work'] },
    ],
  },
  {
    slug: 'full-stack-development',
    icon: '</>',
    title: 'Full Stack Development',
    tone: 'green',
    gridDescription: 'Build modern web applications.',
    badge: 'INDUSTRY READY COURSE',
    tagline: 'MERN Stack development for real-world web applications',
    duration: '5 Months',
    mode: 'Physical & Online Live Classes (Day/Night)',
    overview: [
      'The Full Stack Development course trains you to build complete web applications end to end using JavaScript across both the front end and back end. You will work with React on the client side and Node.js, Express and MongoDB on the server side.',
      'The course focuses on practical, project-based learning so you leave with real applications in your portfolio, along with the debugging, deployment and version-control skills employers expect from a job-ready developer.',
    ],
    tools: ['JavaScript (ES6+)', 'React', 'Node.js', 'Express', 'MongoDB', 'Git / GitHub', 'TailwindCSS', 'Postman', 'Redux Toolkit'],
    curriculum: [
      { title: 'Lesson 1: JavaScript & Git Foundations', topics: ['Modern JavaScript (ES6+)', 'Git & GitHub workflow', 'Dev environment setup'] },
      { title: 'Lesson 2: Frontend with React', topics: ['Components & hooks', 'State management', 'Routing & forms'] },
      { title: 'Lesson 3: Backend with Node & Express', topics: ['REST API design', 'Authentication & middleware', 'Error handling'] },
      { title: 'Lesson 4: Database with MongoDB', topics: ['Schema design', 'Mongoose queries', 'Relationships & indexing'] },
      { title: 'Lesson 5: Full Stack Capstone Project', topics: ['Connecting frontend & backend', 'Deployment', 'Code review & testing'] },
    ],
  },
  {
    slug: 'django-development',
    icon: 'dj',
    title: 'Django Development',
    tone: 'cyan',
    gridDescription: 'Create powerful web solutions.',
    badge: 'BACKEND SPECIALIST COURSE',
    tagline: 'Build secure, scalable web apps with Python & Django',
    duration: '4 Months',
    mode: 'Physical & Online Live Classes (Day/Night)',
    overview: [
      'This Django Development course teaches you to build robust, secure web applications using Python and the Django framework. You will learn Django\'s "batteries-included" approach to authentication, admin panels, forms and database models.',
      'By the end of the course, you will have built and deployed a multi-feature web application, and you will understand how to structure Django projects the way production teams do.',
    ],
    tools: ['Python', 'Django', 'Django REST Framework', 'PostgreSQL', 'HTML/CSS', 'Git / GitHub', 'Docker', 'Postman'],
    curriculum: [
      { title: 'Lesson 1: Python & Django Basics', topics: ['Python refresher', 'Django project structure', 'URLs, views & templates'] },
      { title: 'Lesson 2: Models & Databases', topics: ['ORM & migrations', 'PostgreSQL integration', 'Admin panel customization'] },
      { title: 'Lesson 3: Authentication & Forms', topics: ['User auth & permissions', 'Django forms', 'Session & token auth'] },
      { title: 'Lesson 4: Building REST APIs', topics: ['Django REST Framework', 'Serializers & viewsets', 'API testing with Postman'] },
      { title: 'Lesson 5: Deployment Project', topics: ['Dockerizing the app', 'Deploying to production', 'Final capstone project'] },
    ],
  },
  {
    slug: 'ccna-networking',
    icon: '⌁',
    title: 'CCNA Networking',
    tone: 'slate',
    gridDescription: 'Learn, configure and get certified.',
    badge: 'CERTIFICATION COURSE',
    tagline: 'Networking fundamentals and hands-on router/switch labs',
    duration: '3 Months',
    mode: 'Physical & Online Live Classes (Day/Night)',
    overview: [
      'The CCNA Networking course prepares you for a career in networking and for the Cisco CCNA certification exam. You will learn how networks are designed, addressed and secured, using real router and switch labs alongside the theory.',
      'The course is taught by certified instructors and combines simulation software with live equipment practice, so you graduate confident in configuring and troubleshooting real network infrastructure.',
    ],
    tools: ['Cisco Packet Tracer', 'GNS3', 'Wireshark', 'Cisco IOS', 'Subnetting Tools', 'PuTTY'],
    curriculum: [
      { title: 'Lesson 1: Networking Fundamentals', topics: ['OSI & TCP/IP models', 'IP addressing & subnetting', 'Network topologies'] },
      { title: 'Lesson 2: Switching Concepts', topics: ['VLANs & trunking', 'Spanning Tree Protocol', 'Switch configuration labs'] },
      { title: 'Lesson 3: Routing Concepts', topics: ['Static & dynamic routing', 'OSPF fundamentals', 'Router configuration labs'] },
      { title: 'Lesson 4: Network Security & Services', topics: ['ACLs & NAT', 'DHCP & DNS', 'Basic WAN concepts'] },
      { title: 'Lesson 5: Exam Prep & Labs', topics: ['Troubleshooting labs', 'Mock CCNA exams', 'Certification guidance'] },
    ],
  },
  {
    slug: 'python-programming',
    icon: 'py',
    title: 'Python Programming',
    tone: 'blue',
    gridDescription: 'Master the fundamentals of Python.',
    badge: 'BEGINNER FRIENDLY COURSE',
    tagline: 'From Python basics to real automation & data projects',
    duration: '2 Months',
    mode: 'Physical & Online Live Classes (Day/Night)',
    overview: [
      'This Python Programming course is designed for complete beginners as well as anyone who wants a solid foundation before moving into data science, automation or backend development. You will learn Python syntax, data structures and problem solving from the ground up.',
      'Every topic is reinforced with small projects and exercises, so you build real coding confidence instead of just memorizing syntax.',
    ],
    tools: ['Python 3', 'VS Code', 'Jupyter Notebook', 'Git / GitHub', 'pip & virtual environments', 'Pytest'],
    curriculum: [
      { title: 'Lesson 1: Python Basics', topics: ['Variables & data types', 'Operators & control flow', 'Functions & scope'] },
      { title: 'Lesson 2: Data Structures', topics: ['Lists, tuples & dictionaries', 'Sets & comprehensions', 'File handling'] },
      { title: 'Lesson 3: Object-Oriented Python', topics: ['Classes & objects', 'Inheritance & polymorphism', 'Exception handling'] },
      { title: 'Lesson 4: Working with Libraries', topics: ['Using pip & virtual envs', 'Popular standard libraries', 'Intro to automation scripts'] },
      { title: 'Lesson 5: Mini Projects', topics: ['CLI tools', 'Automation project', 'Testing with Pytest'] },
    ],
  },
  {
    slug: 'java-development',
    icon: 'jv',
    title: 'Java Development',
    tone: 'green',
    gridDescription: 'Build robust enterprise applications.',
    badge: 'ENTERPRISE READY COURSE',
    tagline: 'Core Java to Spring Boot for enterprise applications',
    duration: '5 Months',
    mode: 'Physical & Online Live Classes (Day/Night)',
    overview: [
      'This Java Development course takes you from core Java fundamentals to building enterprise-grade applications with the Spring Boot framework. You will learn object-oriented programming, collections, and how large Java systems are structured.',
      'The later modules focus on Spring Boot, REST APIs and database integration, mirroring the kind of backend systems used in real companies.',
    ],
    tools: ['Java (JDK 17+)', 'Spring Boot', 'Maven', 'MySQL', 'IntelliJ IDEA', 'Git / GitHub', 'Postman', 'JUnit'],
    curriculum: [
      { title: 'Lesson 1: Core Java', topics: ['OOP fundamentals', 'Collections framework', 'Exception handling'] },
      { title: 'Lesson 2: Advanced Java', topics: ['Multithreading basics', 'Streams & lambdas', 'File & JDBC basics'] },
      { title: 'Lesson 3: Spring Boot Fundamentals', topics: ['Spring Boot project setup', 'Dependency injection', 'REST controllers'] },
      { title: 'Lesson 4: Database Integration', topics: ['Spring Data JPA', 'MySQL integration', 'Transactions'] },
      { title: 'Lesson 5: Capstone Project', topics: ['Building a full API', 'Testing with JUnit', 'Deployment basics'] },
    ],
  },
  {
    slug: 'reactjs-development',
    icon: '⚛',
    title: 'React.js Development',
    tone: 'cyan',
    gridDescription: 'Create fast, modern web interfaces.',
    badge: 'FRONTEND SPECIALIST COURSE',
    tagline: 'Build fast, modern interfaces with React & Next.js',
    duration: '3 Months',
    mode: 'Physical & Online Live Classes (Day/Night)',
    overview: [
      'This React.js Development course focuses entirely on modern front-end engineering. You will learn components, hooks and state management, then move into React frameworks like Next.js used by real production teams.',
      'By the end, you will be comfortable building fast, responsive, component-driven interfaces and integrating them with real APIs.',
    ],
    tools: ['React', 'Next.js', 'TypeScript', 'TailwindCSS', 'Redux Toolkit', 'React Query', 'Git / GitHub', 'Vite'],
    curriculum: [
      { title: 'Lesson 1: React Fundamentals', topics: ['JSX & components', 'Props & state', 'Event handling'] },
      { title: 'Lesson 2: Hooks & State Management', topics: ['useState & useEffect', 'Custom hooks', 'Redux Toolkit basics'] },
      { title: 'Lesson 3: Routing & Data Fetching', topics: ['React Router / Next.js routing', 'Fetching APIs', 'React Query'] },
      { title: 'Lesson 4: Styling & Performance', topics: ['TailwindCSS', 'Code splitting', 'Performance optimization'] },
      { title: 'Lesson 5: Frontend Project', topics: ['Building a full app UI', 'API integration', 'Deployment'] },
    ],
  },
  {
    slug: 'data-science',
    icon: '◕',
    title: 'Data Science',
    tone: 'slate',
    gridDescription: 'Turn raw data into real insights.',
    badge: 'ANALYTICS FOCUSED COURSE',
    tagline: 'From raw data to insights with Python & statistics',
    duration: '4 Months',
    mode: 'Physical & Online Live Classes (Day/Night)',
    overview: [
      'The Data Science course teaches you how to work with real data — cleaning it, exploring it, visualizing it and building models that generate genuine business insight. It combines Python, statistics and machine learning fundamentals.',
      'You will finish with hands-on experience using the same tools and workflow used by data analysts and junior data scientists in the industry.',
    ],
    tools: ['Python', 'Pandas', 'NumPy', 'Matplotlib / Seaborn', 'Scikit-learn', 'Jupyter Notebook', 'SQL', 'Power BI'],
    curriculum: [
      { title: 'Lesson 1: Python for Data Science', topics: ['NumPy & Pandas basics', 'Data cleaning', 'Working with datasets'] },
      { title: 'Lesson 2: Data Visualization', topics: ['Matplotlib & Seaborn', 'Exploratory data analysis', 'Dashboards with Power BI'] },
      { title: 'Lesson 3: Statistics for Data Science', topics: ['Descriptive statistics', 'Probability basics', 'Hypothesis testing'] },
      { title: 'Lesson 4: Intro to Machine Learning', topics: ['Regression & classification', 'Model evaluation', 'Scikit-learn workflow'] },
      { title: 'Lesson 5: Capstone Analysis Project', topics: ['End-to-end data project', 'Insights presentation', 'Reporting'] },
    ],
  },
  {
    slug: 'cloud-computing',
    icon: '☁',
    title: 'Cloud Computing',
    tone: 'blue',
    gridDescription: 'Deploy and manage apps on the cloud.',
    badge: 'CLOUD READY COURSE',
    tagline: 'Deploy, scale and manage applications on the cloud',
    duration: '3 Months',
    mode: 'Physical & Online Live Classes (Day/Night)',
    overview: [
      'This Cloud Computing course introduces you to how modern applications are hosted, scaled and secured on the cloud. You will get hands-on practice with core cloud services for compute, storage, networking and deployment.',
      'The course is practical by design — you will deploy real applications to the cloud and learn the fundamentals that apply across AWS, Azure and similar platforms.',
    ],
    tools: ['AWS (EC2, S3, IAM)', 'Docker', 'Linux', 'Terraform basics', 'Git / GitHub', 'CI/CD basics', 'Nginx'],
    curriculum: [
      { title: 'Lesson 1: Cloud Fundamentals', topics: ['What is cloud computing', 'IaaS, PaaS & SaaS', 'Cloud provider overview'] },
      { title: 'Lesson 2: Compute & Storage', topics: ['Virtual machines (EC2)', 'Object storage (S3)', 'Load balancing basics'] },
      { title: 'Lesson 3: Containers & Deployment', topics: ['Docker fundamentals', 'Deploying containerized apps', 'Nginx as reverse proxy'] },
      { title: 'Lesson 4: Security & Access', topics: ['IAM & access policies', 'Networking & security groups', 'Monitoring basics'] },
      { title: 'Lesson 5: Deployment Project', topics: ['End-to-end cloud deployment', 'Basic CI/CD pipeline', 'Cost optimization tips'] },
    ],
  },
  {
    slug: 'cybersecurity',
    icon: '⛨',
    title: 'Cybersecurity',
    tone: 'green',
    gridDescription: 'Protect systems from real-world threats.',
    badge: 'SECURITY FOCUSED COURSE',
    tagline: 'Defend systems and networks from real-world threats',
    duration: '4 Months',
    mode: 'Physical & Online Live Classes (Day/Night)',
    overview: [
      'The Cybersecurity course introduces you to how attackers think and how defenders protect systems, networks and applications. You will practice in safe lab environments using industry-standard security tools.',
      'By the end, you will understand core security principles, common attack techniques and the defensive practices organizations rely on to stay protected.',
    ],
    tools: ['Kali Linux', 'Wireshark', 'Nmap', 'Burp Suite', 'Metasploit (lab use)', 'Linux fundamentals', 'Firewalls & VPNs'],
    curriculum: [
      { title: 'Lesson 1: Security Fundamentals', topics: ['CIA triad', 'Common threat types', 'Security terminology'] },
      { title: 'Lesson 2: Network Security', topics: ['Firewalls & VPNs', 'Network scanning with Nmap', 'Packet analysis with Wireshark'] },
      { title: 'Lesson 3: Ethical Hacking Basics', topics: ['Reconnaissance techniques', 'Vulnerability scanning', 'Lab-based exploitation basics'] },
      { title: 'Lesson 4: Web Application Security', topics: ['OWASP Top 10', 'Testing with Burp Suite', 'Secure coding basics'] },
      { title: 'Lesson 5: Security Project', topics: ['Lab-based security assessment', 'Incident response basics', 'Reporting findings'] },
    ],
  },
  {
    slug: 'mobile-app-development',
    icon: '▤',
    title: 'Mobile App Development',
    tone: 'cyan',
    gridDescription: 'Build apps for Android and iOS.',
    badge: 'CROSS-PLATFORM COURSE',
    tagline: 'Build Android & iOS apps from a single codebase',
    duration: '4 Months',
    mode: 'Physical & Online Live Classes (Day/Night)',
    overview: [
      'This Mobile App Development course teaches you to build real, cross-platform mobile applications using React Native, so your code runs on both Android and iOS from a single codebase.',
      'You will learn navigation, device APIs, state management and how to connect your app to real backend services, finishing with a working app you can publish.',
    ],
    tools: ['React Native', 'Expo', 'TypeScript', 'Firebase', 'Redux Toolkit', 'Git / GitHub', 'Figma (for UI)'],
    curriculum: [
      { title: 'Lesson 1: React Native Basics', topics: ['Setting up Expo', 'Core components', 'Styling with Flexbox'] },
      { title: 'Lesson 2: Navigation & State', topics: ['React Navigation', 'State management', 'Forms & validation'] },
      { title: 'Lesson 3: Device Features & APIs', topics: ['Camera & location APIs', 'Push notifications', 'Local storage'] },
      { title: 'Lesson 4: Backend Integration', topics: ['Connecting to Firebase', 'Authentication', 'Realtime data'] },
      { title: 'Lesson 5: App Project & Publishing', topics: ['Building a complete app', 'Testing on real devices', 'Publishing basics'] },
    ],
  },
  {
    slug: 'machine-learning-ai',
    icon: '✦',
    title: 'Machine Learning & AI',
    tone: 'slate',
    gridDescription: 'Train models that learn and predict.',
    badge: 'AI INTEGRATED COURSE',
    tagline: 'Train, evaluate and deploy real machine learning models',
    duration: '5 Months',
    mode: 'Physical & Online Live Classes (Day/Night)',
    overview: [
      'The Machine Learning & AI course teaches you how to build models that learn patterns from data and make predictions. You will cover the full workflow: data preparation, model training, evaluation and deployment.',
      'The course blends theory with practical labs so you understand not just how to call a library function, but why a model behaves the way it does.',
    ],
    tools: ['Python', 'Scikit-learn', 'TensorFlow / Keras', 'Pandas & NumPy', 'Jupyter Notebook', 'Matplotlib', 'Flask (for deployment)'],
    curriculum: [
      { title: 'Lesson 1: ML Foundations', topics: ['Types of machine learning', 'Data preprocessing', 'Feature engineering'] },
      { title: 'Lesson 2: Supervised Learning', topics: ['Regression models', 'Classification models', 'Model evaluation metrics'] },
      { title: 'Lesson 3: Unsupervised Learning', topics: ['Clustering techniques', 'Dimensionality reduction', 'Anomaly detection'] },
      { title: 'Lesson 4: Intro to Deep Learning', topics: ['Neural network basics', 'Working with TensorFlow/Keras', 'Training & tuning'] },
      { title: 'Lesson 5: Deployment Project', topics: ['Packaging a trained model', 'Serving with Flask', 'Final capstone project'] },
    ],
  },
  {
    slug: 'sql-database-management',
    icon: '▦',
    title: 'SQL & Database Management',
    tone: 'blue',
    gridDescription: 'Design and manage relational databases.',
    badge: 'DATA FOUNDATIONS COURSE',
    tagline: 'Design, query and manage relational databases',
    duration: '2 Months',
    mode: 'Physical & Online Live Classes (Day/Night)',
    overview: [
      'This SQL & Database Management course teaches you how to design relational databases and write efficient SQL queries — a core skill for developers, analysts and administrators alike.',
      'You will practice on real datasets, covering everything from basic queries to database design, indexing and performance tuning.',
    ],
    tools: ['MySQL', 'PostgreSQL', 'MySQL Workbench', 'pgAdmin', 'ER Modeling Tools', 'Git / GitHub'],
    curriculum: [
      { title: 'Lesson 1: SQL Basics', topics: ['SELECT, WHERE & ORDER BY', 'Joins & subqueries', 'Aggregate functions'] },
      { title: 'Lesson 2: Database Design', topics: ['ER diagrams', 'Normalization', 'Primary & foreign keys'] },
      { title: 'Lesson 3: Advanced Queries', topics: ['Window functions', 'Views & stored procedures', 'Transactions'] },
      { title: 'Lesson 4: Performance & Administration', topics: ['Indexing strategies', 'Query optimization', 'Backup & restore basics'] },
      { title: 'Lesson 5: Database Project', topics: ['Designing a schema from scratch', 'Populating & querying data', 'Presenting the project'] },
    ],
  },
  {
    slug: 'devops-cicd',
    icon: '∞',
    title: 'DevOps & CI/CD',
    tone: 'green',
    gridDescription: 'Automate builds, tests and deployments.',
    badge: 'AUTOMATION FOCUSED COURSE',
    tagline: 'Automate builds, tests and deployments like a pro team',
    duration: '3 Months',
    mode: 'Physical & Online Live Classes (Day/Night)',
    overview: [
      'The DevOps & CI/CD course teaches you how modern engineering teams automate building, testing and deploying software. You will learn version control workflows, containerization and pipeline automation.',
      'By the end, you will be able to set up a real CI/CD pipeline that takes code from a commit all the way to a live deployment.',
    ],
    tools: ['Git / GitHub Actions', 'Docker', 'Jenkins', 'Linux', 'Kubernetes basics', 'Terraform basics', 'Nginx'],
    curriculum: [
      { title: 'Lesson 1: DevOps Fundamentals', topics: ['DevOps culture & practices', 'Git branching strategies', 'Linux essentials'] },
      { title: 'Lesson 2: Containerization', topics: ['Docker fundamentals', 'Writing Dockerfiles', 'Docker Compose'] },
      { title: 'Lesson 3: CI/CD Pipelines', topics: ['GitHub Actions basics', 'Jenkins pipelines', 'Automated testing in CI'] },
      { title: 'Lesson 4: Orchestration Basics', topics: ['Kubernetes core concepts', 'Deployments & services', 'Scaling basics'] },
      { title: 'Lesson 5: Automation Project', topics: ['Building a full CI/CD pipeline', 'Deploying to a server', 'Monitoring basics'] },
    ],
  },
  {
    slug: 'graphic-designing',
    icon: '✎',
    title: 'Graphic Designing',
    tone: 'cyan',
    gridDescription: 'Craft visuals for brands and products.',
    badge: 'CREATIVE SKILLS COURSE',
    tagline: 'Craft visuals and branding for real clients and brands',
    duration: '3 Months',
    mode: 'Physical & Online Live Classes (Day/Night)',
    overview: [
      'This Graphic Designing course covers the creative and technical skills needed to design logos, branding, social media graphics and print material professionally.',
      'You will work with industry-standard design software and complete real client-style briefs, building a portfolio that shows range across branding, digital and print design.',
    ],
    tools: ['Adobe Photoshop', 'Adobe Illustrator', 'Adobe InDesign', 'Canva', 'Figma', 'Typography Tools'],
    curriculum: [
      { title: 'Lesson 1: Design Foundations', topics: ['Elements & principles of design', 'Color theory', 'Typography basics'] },
      { title: 'Lesson 2: Adobe Illustrator', topics: ['Vector shapes & paths', 'Logo design', 'Icon design'] },
      { title: 'Lesson 3: Adobe Photoshop', topics: ['Photo editing & retouching', 'Layers & masking', 'Compositing'] },
      { title: 'Lesson 4: Branding & Layout', topics: ['Brand identity design', 'Social media graphics', 'Print layout with InDesign'] },
      { title: 'Lesson 5: Portfolio Project', topics: ['Complete brand package', 'Client-style brief', 'Presenting your portfolio'] },
    ],
  },
  {
    slug: 'windows-server-networking',
    icon: '⌘',
    title: 'Windows Server Networking',
    tone: 'slate',
    gridDescription: 'Configure and administer networks.',
    badge: 'ADMIN READY COURSE',
    tagline: 'Configure and administer enterprise Windows networks',
    duration: '3 Months',
    mode: 'Physical & Online Live Classes (Day/Night)',
    overview: [
      'The Windows Server Networking course prepares you to install, configure and manage Windows Server environments used in real offices and enterprises, including user management, file sharing and network services.',
      'Hands-on labs cover Active Directory, DNS, DHCP and basic network security, giving you the practical administration skills IT support and sysadmin roles require.',
    ],
    tools: ['Windows Server', 'Active Directory', 'DNS & DHCP', 'Hyper-V', 'PowerShell', 'Group Policy'],
    curriculum: [
      { title: 'Lesson 1: Windows Server Basics', topics: ['Server installation & roles', 'Server Manager overview', 'PowerShell basics'] },
      { title: 'Lesson 2: Active Directory', topics: ['Users & groups', 'Organizational units', 'Group Policy basics'] },
      { title: 'Lesson 3: Network Services', topics: ['DNS configuration', 'DHCP configuration', 'File & print sharing'] },
      { title: 'Lesson 4: Virtualization Basics', topics: ['Hyper-V fundamentals', 'Creating virtual machines', 'Basic VM networking'] },
      { title: 'Lesson 5: Admin Project', topics: ['Setting up a small office network', 'User & access management', 'Basic troubleshooting'] },
    ],
  },
];

export function getCourseBySlug(slug: string) {
  return courses.find(course => course.slug === slug);
}
